# Generated by Django 5.0.2 on 2024-03-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetails',
            name='org_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationdetails',
            name='org_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='organizationdetails',
            name='org_type',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate'), ('individual', 'Individual')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doc_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails'),
        ),
    ]
