# Generated by Django 5.0.2 on 2026-04-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_user_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails'),
        ),
        migrations.AddField(
            model_name='department',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('org', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails')),
            ],
        ),
    ]
