# Generated by Django 5.0.2 on 2024-03-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
