# Generated by Django 5.0.2 on 2024-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
