# Generated by Django 5.0.2 on 2026-04-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientmanagement', '0003_appointment_bp_appointment_temp_appointment_weight_and_more'),
        ('usermanagement', '0006_appointmentslot_org_department_org_qualification_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails'),
        ),
        migrations.AddField(
            model_name='patients',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organizationdetails'),
        ),
    ]
