# Generated by Django 5.0.2 on 2024-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientmanagement', '0003_patients_age_patients_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
